### PR TITLE
Add accessDenied to keycloakObject to enable overriding

### PR DESCRIPTION
**Pull request by pgmorgan**
By adding the line below you enable the user to override the keycloak accessDenied method.

### CODE REVIEW

**Comment by AlanTheRoad** [comment]
Hi @c3s4r !

I was about to open this exact PR but then realized that @pgmorgan had beat me to it!

In our app, we had to extend the `getKeycloakObjectForRealm` method and manually overwrite the `accessDenied` handler on each `keycloak-connect` instance. 

If you are able to approve this PR you will help others avoid having to do this themselves. 

Thanks very much!

**Review by AlanTheRoad — APPROVED** [review]

**Comment by c3s4r** [comment]
Hi, sorry that I haven't been able to take a look at it. I'm assigning it now to @daedmunoz for him to review and merge.

**Review by daedmunoz — APPROVED** [review]

**Comment by c3s4r** [comment]
Published with version 2.1.0

**Comment by AlanTheRoad** [comment]
Thanks so much for the quick response! We should be able to remove that custom code I mentioned by pulling this new release

Many thanks!

**Comment by AlanTheRoad** [comment]
and thanks for building this generally!! Saved me lots of time

**Comment by c3s4r** [comment]
Awesome. It's always good to know that it's useful 👍 ... thanks!

**Pull request merged**
